// ────────────────────────────────────────────────────────────────────────────
// DATA — Indian student figures across NRW & Berlin-region locations.
// Coordinates are real [lat, lon] for each city/campus cluster, used to place
// bubbles on the projected Germany map (see js/map.js).
// ────────────────────────────────────────────────────────────────────────────

const NRW = [
  {id:'aachen',name:'Aachen',region:'nrw',lat:50.7753,lon:6.0839,indianStudents:2366,totalIntl:15270,totalStudents:44892,pctIndian:15.5,gender:{male:72,female:28},tier:'very-high',confirmed:true,
   universities:['RWTH Aachen University','FH Aachen (UAS)','H-BRS Aachen-Bonn IT Center'],
   courses:['Mechanical Engineering','Computer Science','Electrical Engineering','Aerospace Engineering','Materials Science'],
   notes:'RWTH Aachen is Germany\'s 2nd-largest technical university. India is 2nd-largest international group (after China). 2,366 Indians confirmed for WS 2024/25.',
   source:'RWTH Aachen Press Release Dec 2024 ✅'},
  {id:'cologne',name:'Cologne (Köln)',region:'nrw',lat:50.9375,lon:6.9603,indianStudents:1400,totalIntl:5000,totalStudents:43594,pctIndian:28,gender:{male:65,female:35},tier:'high',
   universities:['University of Cologne','TH Köln (Technical University Cologne)','German Sport University Cologne','FOM Köln'],
   courses:['Business Administration','Information Systems','Economics','Computer Science','Physics'],
   notes:'University of Cologne has 5,000+ international students across 6 faculties. TH Köln is NRW\'s largest UAS. Strong Indian presence in business, CS and sciences.',source:'Uni Cologne / Shiksha 2024 (est.)'},
  {id:'duisburg',name:'Duisburg',region:'nrw',lat:51.4344,lon:6.7623,indianStudents:700,totalIntl:5500,totalStudents:25000,pctIndian:12.7,gender:{male:68,female:32},tier:'medium',
   universities:['University of Duisburg-Essen (Duisburg campus)','Hochschule Ruhr West'],
   courses:['Technical Systems Management','Mechatronics','Environmental Engineering','Business Informatics'],
   notes:'UDE Duisburg campus focuses on engineering. No tuition fees. Hochschule Ruhr West (Mülheim/Bottrop) nearby adds applied programs.',source:'UDE International Office (est.)'},
  {id:'essen',name:'Essen',region:'nrw',lat:51.4556,lon:7.0116,indianStudents:600,totalIntl:4200,totalStudents:30000,pctIndian:14.3,gender:{male:67,female:33},tier:'medium',
   universities:['University of Duisburg-Essen (Essen campus)','FOM University of Applied Sciences HQ','Folkwang University of the Arts'],
   courses:['Business Informatics','Medicine & Health Sciences','Computer Science','Economics','Arts & Design'],
   notes:'FOM (Germany\'s largest private uni, 47,000+ students, HQ Essen) has significant Indian evening/weekend program enrollment. UDE Essen campus strong in medicine.',source:'UDE Essen / FOM 2024 (est.)'},
  {id:'bochum',name:'Bochum',region:'nrw',lat:51.4818,lon:7.2162,indianStudents:750,totalIntl:6500,totalStudents:38872,pctIndian:11.5,gender:{male:69,female:31},tier:'medium',
   universities:['Ruhr University Bochum (RUB)','Hochschule Bochum','Westfälische Hochschule (Bochum)'],
   courses:['Computational Engineering','Mechanical Engineering','Applied Computer Science','Sales Engineering','Physics'],
   notes:'RUB has ~6,500 international students from 130 countries. Popular Indian MS: Computational Engineering, Mechanical Engineering, Applied CS.',source:'RUB / Goethe Institut 2024 (est.)'},
  {id:'dortmund',name:'Dortmund',region:'nrw',lat:51.5136,lon:7.4653,indianStudents:466,totalIntl:3800,totalStudents:34500,pctIndian:12.3,gender:{male:70,female:30},tier:'medium',confirmed:true,
   universities:['TU Dortmund University','FH Dortmund','ISM International School of Management'],
   courses:['Automation & Robotics','Data Science','Computer Science','Sustainable Energy Systems','Chemical Engineering'],
   notes:'Indians are #1 international group at TU Dortmund, ahead of China & Turkey. ~90% in Master\'s programs. 30% female ratio. 68 graduates in 2023/24.',
   source:'TU Dortmund Official Report Mar 2025 ✅'},
  {id:'duesseldorf',name:'Düsseldorf',region:'nrw',lat:51.2277,lon:6.7735,indianStudents:680,totalIntl:5500,totalStudents:48000,pctIndian:12.4,gender:{male:63,female:37},tier:'medium',
   universities:['Heinrich Heine University (HHU)','Hochschule Düsseldorf (HSD)','FOM Düsseldorf'],
   courses:['Business Administration','Medical Informatics','Computer Science','Social Sciences','Media & Design'],
   notes:'NRW state capital. HSD is 2nd-largest UAS in NRW. HHU strong for medicine & natural sciences. Indian students mainly in business/IT.',source:'HSD / HHU 2024 (est.)'},
  {id:'bonn',name:'Bonn',region:'nrw',lat:50.7374,lon:7.0982,indianStudents:900,totalIntl:4200,totalStudents:31318,pctIndian:21.4,gender:{male:66,female:34},tier:'medium',
   universities:['University of Bonn','H-BRS Bonn-Rhine-Sieg UAS (Sankt Augustin/Rheinbach/Hennef)'],
   courses:['Life & Medical Sciences','Mathematics','Computer Science','Agricultural Sciences','Physics'],
   notes:'Uni Bonn is an Excellence Initiative member with 5 Clusters. H-BRS (9,000 students) has strong IGCHE programme. Indian CS & engineering students particularly at Sankt Augustin.',source:'Uni Bonn / H-BRS 2024 (est.)'},
  {id:'muenster',name:'Münster',region:'nrw',lat:51.9607,lon:7.6261,indianStudents:520,totalIntl:3200,totalStudents:43098,pctIndian:16.3,gender:{male:64,female:36},tier:'medium',
   universities:['University of Münster (WWU)','FH Münster'],
   courses:['Law','Business Administration','Mathematics','Chemistry','IT & Computer Science'],
   notes:'WWU ranks 3rd-best German university (Leiden ranking). 43,000+ students. Growing Indian community in business & sciences.',source:'Uni Münster 2024 (est.)'},
  {id:'bielefeld',name:'Bielefeld',region:'nrw',lat:52.0302,lon:8.5325,indianStudents:350,totalIntl:2600,totalStudents:27000,pctIndian:13.5,gender:{male:67,female:33},tier:'low',
   universities:['University of Bielefeld','FH Bielefeld (Hochschule Bielefeld)'],
   courses:['Intelligent Systems','Data Science','Cognitive Informatics','Biotechnology','Business Informatics'],
   notes:'Bielefeld University known for interdisciplinary research & Intelligent Systems. Growing Indian student community.',source:'Uni Bielefeld / CHE 2024 (est.)'},
  {id:'wuppertal',name:'Wuppertal',region:'nrw',lat:51.2562,lon:7.1508,indianStudents:280,totalIntl:2200,totalStudents:21000,pctIndian:12.7,gender:{male:70,female:30},tier:'low',
   universities:['Bergische Universität Wuppertal (BUW)'],
   courses:['Electrical Engineering','Computer Engineering','Mathematics','Civil Engineering','Safety Engineering'],
   notes:'BUW is growing for Indian engineering students. Affordable living vs. nearby Cologne/Düsseldorf. Distinctive Safety Engineering program.',source:'BUW 2024 (est.)'},
  {id:'paderborn',name:'Paderborn',region:'nrw',lat:51.7189,lon:8.7575,indianStudents:220,totalIntl:1800,totalStudents:20000,pctIndian:12.2,gender:{male:71,female:29},tier:'low',
   universities:['University of Paderborn'],
   courses:['Computer Science','Electrical Engineering','Mechatronics','Business Computing','Mathematics'],
   notes:'Strong CS & EE reputation. Mid-size destination for Indian tech students with lower cost of living.',source:'Uni Paderborn / DAAD 2024 (est.)'},
  {id:'siegen',name:'Siegen',region:'nrw',lat:50.8747,lon:8.0243,indianStudents:160,totalIntl:1400,totalStudents:18618,pctIndian:11.4,gender:{male:69,female:31},tier:'low',
   universities:['University of Siegen'],
   courses:['Mechanical Engineering','Electrical Engineering','Computer Science','Media Studies','Economics'],
   notes:'Active Indian Student Association (inaugurated by Embassy of India). Lower living costs in Siegerland region.',source:'Uni Siegen / Embassy of India 2024 (est.)'},
  {id:'krefeld',name:'Krefeld / Mönchengladbach',region:'nrw',lat:51.3388,lon:6.5853,indianStudents:190,totalIntl:1600,totalStudents:13085,pctIndian:11.9,gender:{male:65,female:35},tier:'low',
   universities:['Hochschule Niederrhein (HS Niederrhein)'],
   courses:['Electrical Engineering & CS','Business Administration','Chemistry','Design','Social Studies'],
   notes:'HS Niederrhein has 13,000+ students across Krefeld and Mönchengladbach. Industry-oriented applied programs.',source:'HS Niederrhein 2024 (est.)'},
  {id:'hagen',name:'Hagen',region:'nrw',lat:51.3671,lon:7.4633,indianStudents:210,totalIntl:2800,totalStudents:70000,pctIndian:7.5,gender:{male:68,female:32},tier:'low',
   universities:['FernUniversität in Hagen (Distance Uni)','FH Südwestfalen (Hagen campus)'],
   courses:['Computer Science','Mathematics','Law','Business Administration','Electrical Engineering'],
   notes:'FernUniversität is Germany\'s largest university (70,000+ students) — entirely distance learning. Lower Indian enrollment due to German-language requirements, but growing.',source:'FernUniversität 2024 (est.)'},
  {id:'hamm',name:'Hamm / Lippstadt',region:'nrw',lat:51.6805,lon:7.8145,indianStudents:95,totalIntl:580,totalStudents:4700,pctIndian:16.4,gender:{male:70,female:30},tier:'very-low',
   universities:['Hochschule Hamm-Lippstadt (HSHL)'],
   courses:['Electronic Engineering','Electrical Engineering','Computer Science','Environmental Engineering','Business'],
   notes:'HSHL (founded 2009, ~4,700 students). Small but growing Indian community. Hands-on engineering programs across Hamm and Lippstadt campuses.',source:'HSHL 2024 (est.)'},
  {id:'gelsenkirchen',name:'Gelsenkirchen',region:'nrw',lat:51.5177,lon:7.0857,indianStudents:130,totalIntl:765,totalStudents:9000,pctIndian:17,gender:{male:71,female:29},tier:'low',
   universities:['Westfälische Hochschule (WH) — Gelsenkirchen, Bocholt, Recklinghausen'],
   courses:['Computer Science','Mechanical Engineering','Energy Systems','Bioengineering','Mechatronics'],
   notes:'WH (~9,000 students, ~8.5% international) is part of IGCHE Indo-German engineering programme. Gelsenkirchen known as "Solar City" with strong renewable energy focus.',source:'Westfälische Hochschule / IGCHE 2024 (est.)'},
  {id:'iserlohn',name:'Iserlohn / Meschede / Soest',region:'nrw',lat:51.3752,lon:7.7013,indianStudents:140,totalIntl:1200,totalStudents:12000,pctIndian:11.7,gender:{male:69,female:31},tier:'low',
   universities:['Fachhochschule Südwestfalen (5 campuses)'],
   courses:['Mechanical Engineering','Electrical Engineering','Agriculture','Computer Science','Business Management'],
   notes:'FH Südwestfalen spans Iserlohn (main), Hagen, Meschede, Soest & Lüdenscheid. Growing Indian cohort across engineering and agriculture programs.',source:'FH Südwestfalen 2024 (est.)'},
  {id:'kleve',name:'Kleve / Kamp-Lintfort',region:'nrw',lat:51.7887,lon:6.1427,indianStudents:120,totalIntl:1400,totalStudents:7500,pctIndian:8.6,gender:{male:66,female:34},tier:'low',
   universities:['Hochschule Rhein-Waal (Kleve & Kamp-Lintfort)'],
   courses:['Life Sciences','Technology & Bionics','Society & Economics','Digital Technologies','Agri-Horticulture'],
   notes:'HS Rhein-Waal notable for high international student share and English-taught programs near Dutch border. Growing Indian presence.',source:'HS Rhein-Waal 2024 (est.)'},
  {id:'steinfurt',name:'Steinfurt',region:'nrw',lat:52.1483,lon:7.3389,indianStudents:110,totalIntl:980,totalStudents:14000,pctIndian:11.2,gender:{male:68,female:32},tier:'very-low',
   universities:['FH Münster (Steinfurt & Münster campuses)'],
   courses:['Civil Engineering','Electrical Engineering','Environmental Engineering','Business','Social Work'],
   notes:'FH Münster is a large NRW UAS. Steinfurt campus focuses on technical disciplines. Indian students mainly in engineering programs.',source:'FH Münster 2024 (est.)'},
  {id:'lemgo',name:'Lemgo / Detmold / Höxter',region:'nrw',lat:51.9366,lon:8.8770,indianStudents:80,totalIntl:620,totalStudents:5672,pctIndian:12.9,gender:{male:67,female:33},tier:'very-low',
   universities:['TH OWL — Technische Hochschule Ostwestfalen-Lippe'],
   courses:['Mechanical Engineering','Electrical Engineering','Architecture & Design','Agri-Food-Health','Media & Culture'],
   notes:'TH OWL (5,672 students) spans Lemgo, Detmold & Höxter. Detmold has the "Detmold School of Design." Small Indian cohort mainly in engineering.',source:'TH OWL 2024 (est.)'},
  {id:'gummersbach',name:'Gummersbach',region:'nrw',lat:51.0273,lon:7.5658,indianStudents:115,totalIntl:1050,totalStudents:11500,pctIndian:10.9,gender:{male:69,female:31},tier:'very-low',
   universities:['TH Köln — Gummersbach Campus (CS & Engineering)'],
   courses:['Computer Science','Media Informatics','Electrical Engineering','Mechanical Engineering','Automation'],
   notes:'TH Köln\'s Gummersbach campus specialises in CS and Engineering. Indian students who prefer quieter campus life near Cologne.',source:'TH Köln 2024 (est.)'},
  {id:'juelich',name:'Jülich',region:'nrw',lat:50.9219,lon:6.3624,indianStudents:90,totalIntl:820,totalStudents:5000,pctIndian:11,gender:{male:73,female:27},tier:'very-low',
   universities:['FH Aachen — Jülich Campus','Forschungszentrum Jülich (FZJ — research/PhD)'],
   courses:['Energy Technology','Biomedical Engineering','Scientific Programming','Physics','Chemistry'],
   notes:'Jülich has one of Europe\'s largest research centres (FZJ) attracting Indian PhD researchers. FH Aachen Jülich campus specialises in energy & biomedical tech.',source:'FH Aachen Jülich / FZJ 2024 (est.)'},
];

const BERLIN = [
  {id:'tu-berlin',name:'TU Berlin (Charlottenburg)',region:'berlin',lat:52.5125,lon:13.3269,indianStudents:1800,totalIntl:10000,totalStudents:33000,pctIndian:18,gender:{male:74,female:26},tier:'very-high',
   universities:['Technische Universität Berlin (TU Berlin)'],
   courses:['Computer Science','Electrical Engineering','Mechanical Engineering','Architecture','Innovation Management & Entrepreneurship'],
   notes:'TU Berlin has 10,000+ foreign nationals (WS 2024/25) — one of highest intl % in Germany (>25%). India is among top 3 source countries. Strong MS programs in English. TU9 member & Excellence University.',
   source:'TU Berlin / Shiksha WS 2024/25 (est. ~18% of intl = India)'},
  {id:'fu-berlin',name:'FU Berlin (Dahlem)',region:'berlin',lat:52.4536,lon:13.2880,indianStudents:620,totalIntl:6000,totalStudents:35000,pctIndian:10.3,gender:{male:58,female:42},tier:'medium',
   universities:['Freie Universität Berlin (FU Berlin)','Charité — Universitätsmedizin Berlin (joint)'],
   courses:['Life Sciences','Social Sciences','Humanities','Mathematics & CS','Law'],
   notes:'FU Berlin is an Excellence Initiative university (Berlin University Alliance). Strong for humanities, social & life sciences. Higher female ratio than other German universities. Charité partnership for medicine.',
   source:'FU Berlin 2024 (est.)'},
  {id:'hu-berlin',name:'HU Berlin (Mitte)',region:'berlin',lat:52.5183,lon:13.3936,indianStudents:480,totalIntl:6013,totalStudents:34540,pctIndian:8,gender:{male:60,female:40},tier:'medium',
   universities:['Humboldt-Universität zu Berlin (HU Berlin)'],
   courses:['Philosophy & Humanities','Law','Life Sciences','Business & Economics','Mathematics & Natural Sciences'],
   notes:'HU Berlin (founded 1810) is one of Europe\'s most prestigious universities. 6,013 international students (17.4% of 34,540). German-language requirement limits Indian enrollment vs. TU Berlin.',
   source:'HU Berlin / Collegedunia Apr 2026 (est.)'},
  {id:'htw-berlin',name:'HTW Berlin (Karlshorst)',region:'berlin',lat:52.4842,lon:13.4700,indianStudents:520,totalIntl:4000,totalStudents:15000,pctIndian:13,gender:{male:68,female:32},tier:'medium',
   universities:['HTW Berlin — Hochschule für Technik und Wirtschaft (UAS)','Beuth University of Applied Sciences (BHT)'],
   courses:['Mechanical Engineering','Automotive Engineering','Business Administration','Game Design','Facility Management'],
   notes:'HTW Berlin is the largest UAS in Berlin (15,000 students, 25% international). Beuth/BHT has 12,000+ students strong in technology & engineering. Both attract Indian engineering students.',
   source:'HTW Berlin / MyGermanUniversity 2024 (est.)'},
  {id:'hwr-berlin',name:'HWR Berlin (Schöneberg)',region:'berlin',lat:52.4827,lon:13.3559,indianStudents:310,totalIntl:3200,totalStudents:11000,pctIndian:9.7,gender:{male:62,female:38},tier:'low',
   universities:['HWR Berlin — Berlin School of Economics & Law'],
   courses:['Business Administration','MBA & MIM','Public Administration','Security Management','Law'],
   notes:'HWR Berlin offers strong English-taught MBA & MIM programs. Attracts Indian business students. Located in Schöneberg (West Berlin) and Lichtenberg (East Berlin) campuses.',
   source:'HWR Berlin / MyGermanUniversity 2024 (est.)'},
  {id:'esmt-berlin',name:'ESMT & Private Unis (Berlin)',region:'berlin',lat:52.5085,lon:13.3838,indianStudents:190,totalIntl:2200,totalStudents:5000,pctIndian:8.6,gender:{male:65,female:35},tier:'low',
   universities:['ESMT Berlin (Business School)','SRH Berlin University of Applied Sciences','Berlin International UAS','GISMA Business School'],
   courses:['MBA & Executive MBA','Entrepreneurship','Computer Science','Media & Design','Finance'],
   notes:'ESMT Berlin is a triple-accredited business school attracting Indian MBA students. SRH Berlin is fully English-taught, popular with Indian undergrads. GISMA has practical business programs.',
   source:'ESMT / SRH Berlin 2024 (est.)'},
  {id:'udk-berlin',name:'UdK & Arts (Berlin)',region:'berlin',lat:52.5090,lon:13.3272,indianStudents:95,totalIntl:1400,totalStudents:3500,pctIndian:6.8,gender:{male:44,female:56},tier:'very-low',
   universities:['Universität der Künste Berlin (UdK)','Kunsthochschule Berlin-Weißensee','Hochschule für Schauspielkunst "Ernst Busch"'],
   courses:['Fine Arts','Music','Architecture & Design','Performing Arts','Visual Communication'],
   notes:'UdK is Europe\'s largest art university. Relatively smaller Indian student community but present in design & architecture. Higher female ratio in arts.',
   source:'UdK Berlin 2024 (est.)'},
  {id:'potsdam',name:'Potsdam (Brandenburg)',region:'berlin',lat:52.3906,lon:13.0645,indianStudents:210,totalIntl:2800,totalStudents:21000,pctIndian:7.5,gender:{male:65,female:35},tier:'low',
   universities:['University of Potsdam','HPI — Hasso Plattner Institute'],
   courses:['Computer Science & IT Systems','Digital Engineering','Business & Economics','Cognitive Sciences','Life Sciences'],
   notes:'University of Potsdam (21,000 students) is 20 min from Berlin by train. HPI is a world-class digital engineering school (linked to SAP). Growing Indian presence especially in IT/CS programs.',
   source:'Uni Potsdam / HPI 2024 (est.)'},
  {id:'brandenburgtech',name:'Brandenburg an der Havel',region:'berlin',lat:52.4125,lon:12.5316,indianStudents:85,totalIntl:950,totalStudents:8500,pctIndian:8.9,gender:{male:71,female:29},tier:'very-low',
   universities:['Brandenburg University of Technology (BTU Cottbus-Senftenberg)','Technische Hochschule Brandenburg'],
   courses:['Environmental & Resource Management','Electrical Engineering','Computer Science','Business Administration','Architecture'],
   notes:'BTU Cottbus-Senftenberg and TH Brandenburg attract Indian engineering students seeking lower costs and quieter campus environments within the Berlin commuter zone.',
   source:'BTU / TH Brandenburg 2024 (est.)'},
];

const ALL = [...NRW, ...BERLIN];
